# Generated by Django 5.1.4 on 2024-12-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('continent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.continent')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.country'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default=None)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=50)),
                ('departure_date', models.DateField(default=None)),
                ('return_date', models.DateField(default=None)),
                ('duration', models.IntegerField(default=None)),
                ('type', models.CharField(max_length=2)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('promoted', models.BooleanField(default=False)),
                ('adult_places', models.IntegerField(default=None)),
                ('child_places', models.IntegerField(default=None)),
                ('where_from', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='where_from', to='viewer.airport')),
                ('where_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.airport')),
                ('where_to_hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='where_to', to='viewer.hotel')),
            ],
        ),
    ]
