# Generated by Django 5.1.4 on 2024-12-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('AI', 'AI')], default=None, max_length=20),
        ),
    ]
