# Generated by Django 5.1.4 on 2024-12-19 20:39

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_country_continent_delete_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AddField(
            model_name='city',
            name='continent',
            field=models.CharField(choices=[('------', '------'), ('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Australia & Oceania', 'Australia & Oceania'), ('South America', 'South America')], default='------', max_length=20),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
