# Generated by Django 5.1.4 on 2024-12-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_trip_airport_arriv_trip_airport_depat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='airport_arriv',
            new_name='airport_arrive',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='airport_depat',
            new_name='airport_depart',
        ),
    ]
