# Generated by Django 5.1.4 on 2024-12-21 18:16

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_rename_airport_arriv_trip_airport_arrive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='airport_arrive',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='where_to', chained_model_field='name', help_text='Choose an airport', on_delete=django.db.models.deletion.CASCADE, related_name='airport_arrive', to='viewer.airport'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='airport_depart',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='where_from', chained_model_field='name', help_text='Choose an airport', on_delete=django.db.models.deletion.CASCADE, related_name='airport_depart', to='viewer.airport'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='where_from',
            field=models.ForeignKey(default=None, help_text='Choose a city', on_delete=django.db.models.deletion.DO_NOTHING, related_name='where_from', to='viewer.city'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='where_to',
            field=models.ForeignKey(default=None, help_text='Choose a city', on_delete=django.db.models.deletion.DO_NOTHING, related_name='where_to', to='viewer.city'),
        ),
    ]
