# Generated by Django 5.1.4 on 2024-12-21 20:36

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_trip_airport_arrive_alter_trip_airport_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='airport_arrive',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='city', help_text='Choose an airport', on_delete=django.db.models.deletion.CASCADE, related_name='airport_arrive', to='viewer.airport'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='airport_depart',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='city', help_text='Choose an airport', on_delete=django.db.models.deletion.CASCADE, related_name='airport_depart', to='viewer.airport'),
        ),
    ]
