# Generated by Django 5.1.4 on 2024-12-21 20:44

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_alter_trip_airport_arrive_alter_trip_airport_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='airport_arrive',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='where_to', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, related_name='airport_arrive', to='viewer.airport'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='airport_depart',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='where_from', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, related_name='airport_depart', to='viewer.airport'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='where_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='where_from', to='viewer.city'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='where_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='where_to', to='viewer.city'),
        ),
    ]
