# Generated by Django 5.1.4 on 2024-12-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_alter_trip_airport_arrive_alter_trip_airport_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Australia & Oceania', 'Australia & Oceania'), ('South America', 'South America')], help_text='Choose a continent', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('AI', 'AI')], default=None, help_text='Choose a type of the trip', max_length=20),
        ),
    ]
