# Generated by Django 5.1.4 on 2024-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_alter_city_continent_alter_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Australia & Oceania', 'Australia & Oceania'), ('South America', 'South America')], default='select continent', max_length=20),
        ),
    ]
