# Generated by Django 5.1.4 on 2024-12-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_city_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='continent',
            field=models.CharField(blank=True, choices=[(None, 'select continent'), ('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Australia & Oceania', 'Australia & Oceania'), ('South America', 'South America')], max_length=30),
        ),
    ]
