# Generated by Django 5.1.4 on 2024-12-22 11:32

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_alter_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='where_to_hotel',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='where_to_hotel', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='viewer.hotel'),
        ),
    ]
