# Generated by Django 5.1.4 on 2024-12-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_alter_trip_where_to_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'select type of stay'), ('BB', 'bed & breakfast'), ('HB', 'half board'), ('FB', 'full board'), ('AI', 'all inclusive')], max_length=20),
        ),
    ]
