# Generated by Django 5.1.4 on 2024-12-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0025_alter_trip_adult_places_alter_trip_adult_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='trip',
            name='image_small',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='trip',
            name='short_description',
            field=models.TextField(default=None),
        ),
    ]
