# Generated by Django 5.1.4 on 2024-12-30 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_trip_description_trip_image_trip_image_small_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchsedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('birth_date', models.DateField(default=None)),
                ('amount_adult', models.IntegerField(default=None)),
                ('amount_child', models.IntegerField(default=None)),
                ('trip', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.trip')),
            ],
        ),
    ]
