# Generated by Django 5.1.4 on 2024-12-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_purchsedtrip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchsedTrip',
            new_name='PurchasedTrip',
        ),
    ]
