# Generated by Django 5.1.4 on 2025-01-05 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0028_rename_purchsedtrip_purchasedtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtrip',
            name='email',
            field=models.EmailField(default='your@email.domain', max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='purchasedtrip',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
