# Generated by Django 5.1.4 on 2025-01-05 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_remove_hotel_standard_purchasedtrip_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtrip',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
