# Generated by Django 5.1.4 on 2025-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0030_remove_hotel_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtrip',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
    ]
