# Generated by Django 5.1.4 on 2025-01-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0032_remove_hotel_standard_alter_trip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
