# Generated by Django 5.1.4 on 2025-01-15 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0033_remove_hotel_standard_alter_trip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='code',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
