# Generated by Django 5.1.4 on 2025-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0034_remove_hotel_standard_alter_trip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image_small',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
