# Generated by Django 5.1.4 on 2025-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0035_alter_trip_image_alter_trip_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtrip',
            name='email',
            field=models.EmailField(default=None, max_length=70, unique=True),
        ),
    ]
