# Generated by Django 5.1.4 on 2025-01-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0036_alter_purchasedtrip_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='type',
            new_name='service_standard',
        ),
    ]
