# Generated by Django 5.1.4 on 2025-01-26 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0037_rename_type_trip_service_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtrip',
            name='email',
            field=models.EmailField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='purchasedtrip',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='service_standard',
            field=models.CharField(choices=[(None, 'select service standard'), ('BB', 'bed & breakfast'), ('HB', 'half board'), ('FB', 'full board'), ('AI', 'all inclusive')], max_length=20),
        ),
    ]
